/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.dreptschar.plantmanagerbackend.adapter.inbound.rest.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-13T15:35:07.946460567Z[Etc/UTC]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "Action Types", description = "the Action Types API")
public interface ActionTypesApi {

    /**
     * GET /action-types : List action types
     *
     * @return Action type list (status code 200)
     */
    @Operation(
        operationId = "actionTypesGet",
        summary = "List action types",
        tags = { "Action Types" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Action type list")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/action-types"
    )
    
    default ResponseEntity<Void> actionTypesGet(
        
    ) {
        return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build();
    }

}
