CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE action_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE plants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    species VARCHAR(255),
    room_id BIGINT,
    notes TEXT,
    photo_path VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_plants_room
        FOREIGN KEY (room_id)
        REFERENCES rooms (id)
        ON DELETE SET NULL
);

CREATE TABLE plant_action_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT NOT NULL,
    action_type_id BIGINT NOT NULL,
    interval_days INTEGER NOT NULL CHECK (interval_days > 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_triggered_at TIMESTAMP,
    next_due_at TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_plant_action_plans_plant
        FOREIGN KEY (plant_id)
        REFERENCES plants (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_plant_action_plans_action_type
        FOREIGN KEY (action_type_id)
        REFERENCES action_types (id)
        ON DELETE RESTRICT
);

CREATE TABLE plant_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT NOT NULL,
    action_type_id BIGINT NOT NULL,
    action_plan_id BIGINT,
    performed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_plant_actions_plant
        FOREIGN KEY (plant_id)
        REFERENCES plants (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_plant_actions_action_type
        FOREIGN KEY (action_type_id)
        REFERENCES action_types (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_plant_actions_action_plan
        FOREIGN KEY (action_plan_id)
        REFERENCES plant_action_plans (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_plants_room_id ON plants (room_id);
CREATE INDEX idx_plant_action_plans_plant_id ON plant_action_plans (plant_id);
CREATE INDEX idx_plant_action_plans_action_type_id ON plant_action_plans (action_type_id);
CREATE INDEX idx_plant_action_plans_enabled ON plant_action_plans (enabled);
CREATE INDEX idx_plant_actions_plant_id ON plant_actions (plant_id);
CREATE INDEX idx_plant_actions_action_type_id ON plant_actions (action_type_id);
CREATE INDEX idx_plant_actions_action_plan_id ON plant_actions (action_plan_id);
CREATE INDEX idx_plant_actions_performed_at ON plant_actions (performed_at);

INSERT INTO action_types (code, name, description) VALUES
    ('WATERING', 'Watering', 'Water the plant'),
    ('FERTILIZING', 'Fertilizing', 'Fertilize the plant');
